# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image with pnpm installed
FROM node:18-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Set the working directory
WORKDIR /app

# Copy the project files to the container
COPY . .

# Install dependencies and build the project
RUN pnpm install && pnpm build

# Expose any necessary ports (if applicable)
# ENV IDE_PORT=8000
# ENV HOST=0.0.0.0

# Define the command to run the application
ENTRYPOINT ["node", "dist/src/index.js"]
